version: "3"
services:
  node:
    image: node:latest
    restart: unless-stopped
    volumes:
      - ./:/app
    command: tail -F /dev/null
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
        - ./var/dbdata:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
